server:
  port: 8088

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
            maxAge: 30
      routes:
      - id: test
        uri: http://dev2.neogiciel.com
        predicates:
        - Path=/test
#     - id: security
#       uri: http://dev2.neogiciel.com
#       predicates:
#       - Path=/security
#     - id: test
#       uri: http://dev2.neogiciel.com
#       predicates:
#       - Path=/test/**
#  
#prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      show-details: always
  metrics:
    tags:
      application: MonitoringGateway
